import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import './globals.css'

import Navbar from '@/components/Navbar'
import Provider from '@/lib/provider'

export const metadata: Metadata = {
  title: 'Wongnok',
  description: 'Generated by create next app',
}

const prompt = Prompt({
  subsets: ['thai'],
  weight: ['400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={prompt.className}>
      <body className={prompt.className}>
        <main>
          <Provider>
            <Navbar />
            {children}
          </Provider>
        </main>
        <footer></footer>
      </body>
    </html>
  )
}
